default:
  just --list

build:
  ./gradlew buildAndroidLib
  cd ../bbqr-ffi && just gen-android

clean:
  rm -rf ../bbqr-ffi/target/
  rm -rf ./build/
  rm -rf ./lib/build/
  rm -rf ./plugins/build/

publish-local:
  ./gradlew publishToMavenLocal -P localBuild
