gen:
  just gen-android
  just gen-swift

gen-android:
  cargo ndk --target aarch64-linux-android build --package bbqr-ffi 
  cargo run --bin uniffi-bindgen generate --library target/aarch64-linux-android/debug/libbbqrffi.so --config uniffi.toml --language kotlin --out-dir ../bbqr-android/lib/src/main/kotlin --no-format

gen-swift:
  cargo build --package bbqr-ffi
  cargo run --bin uniffi-bindgen generate --library target/debug/libbbqrffi.a --config uniffi.toml --language swift --out-dir ../bbqr-swift/Sources/Bbqr
